In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('Datasets/clientes.csv')

In [5]:
pd.set_option('display.width', None)

In [7]:
df.drop('pais', axis=1, inplace=True)

In [9]:
df.describe

<bound method NDFrame.describe of                          nome             cpf  idade        data  \
0     Sr. Vitor Gabriel Silva  640.719.385-01     90  06/12/1933
1               Calebe Santos  651.297.384-46     40  06/03/1984
2                Evelyn Pires  107.643.528-90     80  09/03/1944
3          Maria Julia Castro  164.750.293-43     76  12/04/1947
4              Arthur da Rosa  085.167.249-30     53  16/04/1970
...                       ...             ...    ...         ...
1022              Lívia Nunes  742.380.591-23     49  14/03/1975
1023              Joana Silva  349.051.867-57     24  19/09/1999
1024              Luigi Porto  826.509.374-83     43  18/08/1980
1025          Letícia da Mata  308.742.169-31     47  04/08/1976
1026         Dr. Thomas Nunes  967.831.542-46     81  14/08/1942

                                               endereco          estado
0     Trevo Emanuel Silva, 482\nVila Tirol\n47847085...        Rondônia
1     Recanto Moraes, 7\nErnesto Nascimento\n96497-6...  Rio de Janeiro
2     Travessa de Caldeira, 237\nSanta Terezinha\n84...         Sergipe
3     Residencial de Pereira, 20\nJatobá\n62127-165 ...      Pernambuco
4     Parque Almeida, 66\nVila Suzana Segunda Seção\...  Santa Catarina
...                                                 ...             ...
1022  Passarela de Porto, 65\nPousada Santo Antonio\...           Bahia
1023  Chácara Miguel Fogaça\nLaranjeiras\n52800515 S...      Pernambuco
1024  Parque de Santos, 88\nSão João\n60112-833 Rodr...  Espírito Santo
1025  Aeroporto da Paz, 54\nVila São Dimas\n26750-50...  Rio de Janeiro
1026  Vereda da Mota, 37\nVila Da Luz\n50836-481 Mou...           Piauí

[1027 rows x 6 columns]>

In [11]:
df.head()

,nome,cpf,idade,data,endereco,estado
0,Sr. Vitor Gabriel Silva,640.719.385-01,90,06/12/1933,"Trevo Emanuel Silva, 482\nVila Tirol\n47847085...",Rondônia
1,Calebe Santos,651.297.384-46,40,06/03/1984,"Recanto Moraes, 7\nErnesto Nascimento\n96497-6...",Rio de Janeiro
2,Evelyn Pires,107.643.528-90,80,09/03/1944,"Travessa de Caldeira, 237\nSanta Terezinha\n84...",Sergipe
3,Maria Julia Castro,164.750.293-43,76,12/04/1947,"Residencial de Pereira, 20\nJatobá\n62127-165 ...",Pernambuco
4,Arthur da Rosa,085.167.249-30,53,16/04/1970,"Parque Almeida, 66\nVila Suzana Segunda Seção\...",Santa Catarina

In [13]:
df.drop(2, axis=0, inplace=True)

In [15]:
df.isnull().sum()

nome         3
cpf          7
idade        0
data        10
endereco     5
estado       5
dtype: int64

In [17]:
df.fillna(0)

,nome,cpf,idade,data,endereco,estado
0,Sr. Vitor Gabriel Silva,640.719.385-01,90,06/12/1933,"Trevo Emanuel Silva, 482\nVila Tirol\n47847085...",Rondônia
1,Calebe Santos,651.297.384-46,40,06/03/1984,"Recanto Moraes, 7\nErnesto Nascimento\n96497-6...",Rio de Janeiro
3,Maria Julia Castro,164.750.293-43,76,12/04/1947,"Residencial de Pereira, 20\nJatobá\n62127-165 ...",Pernambuco
4,Arthur da Rosa,085.167.249-30,53,16/04/1970,"Parque Almeida, 66\nVila Suzana Segunda Seção\...",Santa Catarina
5,Juan Pereira,520.876.319-21,68,25/10/1955,"Rodovia de Pereira, 51\nEstrela\n44830637 Mend...",Rio de Janeiro
...,...,...,...,...,...,...
1022,Lívia Nunes,742.380.591-23,49,14/03/1975,"Passarela de Porto, 65\nPousada Santo Antonio\...",Bahia
1023,Joana Silva,349.051.867-57,24,19/09/1999,Chácara Miguel Fogaça\nLaranjeiras\n52800515 S...,Pernambuco
1024,Luigi Porto,826.509.374-83,43,18/08/1980,"Parque de Santos, 88\nSão João\n60112-833 Rodr...",Espírito Santo
1025,Letícia da Mata,308.742.169-31,47,04/08/1976,"Aeroporto da Paz, 54\nVila São Dimas\n26750-50...",Rio de Janeiro
1026,Dr. Thomas Nunes,967.831.542-46,81,14/08/1942,"Vereda da Mota, 37\nVila Da Luz\n50836-481 Mou...",Piauí

In [58]:
df.head(500)

,nome,cpf,idade,data,endereco,estado
0,Sr. Vitor Gabriel Silva,640.719.385-01,90,06/12/1933,"Trevo Emanuel Silva, 482\nVila Tirol\n47847085...",Rondônia
1,Calebe Santos,651.297.384-46,40,06/03/1984,"Recanto Moraes, 7\nErnesto Nascimento\n96497-6...",Rio de Janeiro
3,Maria Julia Castro,164.750.293-43,76,12/04/1947,"Residencial de Pereira, 20\nJatobá\n62127-165 ...",Pernambuco
4,Arthur da Rosa,085.167.249-30,53,16/04/1970,"Parque Almeida, 66\nVila Suzana Segunda Seção\...",Santa Catarina
5,Juan Pereira,520.876.319-21,68,25/10/1955,"Rodovia de Pereira, 51\nEstrela\n44830637 Mend...",Rio de Janeiro
...,...,...,...,...,...,...
496,Igor Melo,519.307.648-39,97,31/03/1927,Viaduto Nogueira\nGrota\n13502920 Ferreira do ...,São Paulo
497,Sra. Vitória Carvalho,528.049.736-38,35,20/02/1989,"Jardim Fernanda Moura, 767\nCdi Jatoba\n325040...",Mato Grosso
498,Sofia Duarte,412.835.697-28,18,09/07/2005,"Morro Isaac Freitas, 543\nVila Nova Cachoeirin...",Rio Grande do Norte
499,Brenda Nogueira,160.294.358-33,56,23/07/1967,"Pátio de Almeida, 4\nMala E Cuia\n08990015 Ara...",Amazonas
500,Rafael Fogaça,569.137.028-68,93,04/03/1931,"Setor de da Rosa, 401\nNova Vista\n61631-368 C...",Maranhão

In [74]:
df['idade'].mean()

86.80896686159844

In [76]:
df.shape

(1026, 6)

In [21]:
Dados_formatados = df[['nome', 'cpf', 'idade', 'data', 'endereco', 'estado']]
Dados_formatados.to_csv('tabela_clientes.csv', index=False)