In [1]:
import pandas as pd

In [23]:
doc = pd.read_csv('Datasets/Student Depression Dataset.csv')

In [25]:
doc.head(200)

,id,Gender,Age,City,Profession,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Sleep Duration,Dietary Habits,Degree,Have you ever had suicidal thoughts ?,Work/Study Hours,Financial Stress,Family History of Mental Illness,Depression
0,2,Male,33.0,Visakhapatnam,Student,5.0,0.0,8.97,2.0,0.0,5-6 hours,Healthy,B.Pharm,Yes,3.0,1.0,No,1
1,8,Female,24.0,Bangalore,Student,2.0,0.0,5.90,5.0,0.0,5-6 hours,Moderate,BSc,No,3.0,2.0,Yes,0
2,26,Male,31.0,Srinagar,Student,3.0,0.0,7.03,5.0,0.0,Less than 5 hours,Healthy,BA,No,9.0,1.0,Yes,0
3,30,Female,28.0,Varanasi,Student,3.0,0.0,5.59,2.0,0.0,7-8 hours,Moderate,BCA,Yes,4.0,5.0,Yes,1
4,32,Female,25.0,Jaipur,Student,4.0,0.0,8.13,3.0,0.0,5-6 hours,Moderate,M.Tech,Yes,1.0,1.0,No,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,947,Male,33.0,Kanpur,Student,2.0,0.0,9.54,3.0,0.0,7-8 hours,Healthy,MA,No,11.0,4.0,Yes,0
196,949,Female,20.0,Pune,Student,5.0,0.0,6.17,2.0,0.0,More than 8 hours,Healthy,Class 12,Yes,7.0,5.0,Yes,1
197,953,Female,25.0,Agra,Student,2.0,0.0,9.95,1.0,0.0,More than 8 hours,Unhealthy,B.Pharm,Yes,10.0,5.0,No,1
198,955,Male,24.0,Hyderabad,Student,5.0,0.0,9.05,2.0,0.0,7-8 hours,Healthy,B.Tech,Yes,8.0,4.0,Yes,1
199,956,Male,23.0,Agra,Student,4.0,0.0,9.24,2.0,0.0,Less than 5 hours,Healthy,B.Com,Yes,7.0,2.0,No,1