In [2]:
import pandas as pd
from matplotlib import pyplot as plt

In [11]:
Quality_air = pd.read_csv('Datasets/updated_air_quality_data.csv')

In [13]:
Quality_air

,Unique ID,Name,Measure,Geo Type Name,Geo Place Name,Time Period,Start_Date,Data Value,Air Quality Category
0,179772,Emissions,Density,UHF42,Queens,Other,2015-01-01,0.3,Good
1,179785,Emissions,Density,UHF42,Unknown,Other,2015-01-01,1.2,Good
2,178540,General Pollution,Miles,UHF42,Unknown,Annual Average,2011-12-01,8.6,Good
3,178561,General Pollution,Miles,UHF42,Queens,Annual Average,2011-12-01,8.0,Good
4,823217,General Pollution,Miles,UHF42,Queens,Summer,2022-06-01,6.1,Good
...,...,...,...,...,...,...,...,...,...
18011,816914,General Pollution,Miles,CD,Unknown,Other,2019-01-01,12.9,Moderate
18012,816913,General Pollution,Miles,CD,Unknown,Other,2010-01-01,14.7,Moderate
18013,816872,General Pollution,Miles,UHF42,Unknown,Other,2010-01-01,43.4,Bad
18014,816832,General Pollution,Miles,UHF42,Queens,Other,2010-01-01,65.8,Bad
18015,151658,General Pollution,Miles,UHF42,Unknown,Other,2005-01-01,41.0,Bad

In [15]:
Quality_air.shape

(18016, 9)

In [18]:
Quality_air.columns

Index(['Unique ID', 'Name', 'Measure', 'Geo Type Name', 'Geo Place Name',
       'Time Period', 'Start_Date', 'Data Value', 'Air Quality Category'],
      dtype='object')

In [17]:
Quality_air.dtypes

Unique ID                 int64
Name                     object
Measure                  object
Geo Type Name            object
Geo Place Name           object
Time Period              object
Start_Date               object
Data Value              float64
Air Quality Category     object
dtype: object

In [19]:
Quality_air.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18016 entries, 0 to 18015
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unique ID             18016 non-null  int64
 1   Name                  18016 non-null  object
 2   Measure               18016 non-null  object
 3   Geo Type Name         18016 non-null  object
 4   Geo Place Name        18016 non-null  object
 5   Time Period           18016 non-null  object
 6   Start_Date            18016 non-null  object
 7   Data Value            18016 non-null  float64
 8   Air Quality Category  18016 non-null  object
dtypes: float64(1), int64(1), object(7)
memory usage: 1.2+ MB

In [21]:
Quality_air.head()

,Unique ID,Name,Measure,Geo Type Name,Geo Place Name,Time Period,Start_Date,Data Value,Air Quality Category
0,179772,Emissions,Density,UHF42,Queens,Other,2015-01-01,0.3,Good
1,179785,Emissions,Density,UHF42,Unknown,Other,2015-01-01,1.2,Good
2,178540,General Pollution,Miles,UHF42,Unknown,Annual Average,2011-12-01,8.6,Good
3,178561,General Pollution,Miles,UHF42,Queens,Annual Average,2011-12-01,8.0,Good
4,823217,General Pollution,Miles,UHF42,Queens,Summer,2022-06-01,6.1,Good

In [22]:
Quality_air['Name']

0                Emissions
1                Emissions
2        General Pollution
3        General Pollution
4        General Pollution
               ...
18011    General Pollution
18012    General Pollution
18013    General Pollution
18014    General Pollution
18015    General Pollution
Name: Name, Length: 18016, dtype: object

In [23]:
Quality_air[['Name', 'Measure', 'Geo Type Name']]

                    Name  Measure Geo Type Name
0              Emissions  Density         UHF42
1              Emissions  Density         UHF42
2      General Pollution    Miles         UHF42
3      General Pollution    Miles         UHF42
4      General Pollution    Miles         UHF42
...                  ...      ...           ...
18011  General Pollution    Miles            CD
18012  General Pollution    Miles            CD
18013  General Pollution    Miles         UHF42
18014  General Pollution    Miles         UHF42
18015  General Pollution    Miles         UHF42

[18016 rows x 3 columns]