In [7]:
import pandas as pd 
from matplotlib import pyplot as plt

In [3]:
df = pd.read_csv('dataset/netflix_user_v1.csv')

In [5]:
df

,ID_Usuário,Idade,País,Assinaturas,Tempo_assistido,Genero_favorito,Ultimo_Login
0,1,18,France,Premium,80.26,Drama,2024-05-12
1,2,23,USA,Premium,321.75,Ficcao cientifica,2025-02-05
2,3,60,UK,Basico,35.89,Comedia,2025-01-24
3,4,44,USA,Premium,261.56,Documentario,2024-03-25
4,5,68,USA,Padrao,909.30,Drama,2025-01-14
...,...,...,...,...,...,...,...
24995,24996,18,Australia,Premium,183.88,Horror,2025-01-18
24996,24997,17,USA,Premium,112.37,Drama,2024-06-29
24997,24998,14,USA,Premium,351.80,Acao,2024-10-16
24998,24999,71,USA,Basico,655.89,Acao,2024-08-27
24999,25000,19,Germany,Premium,207.06,Documentario,2024-04-12

In [21]:
#Verificando a proporção das categorias de genero

drama = len(df.loc[df['Genero_favorito'] == 'Drama'])
ficcao_cientifica = len(df.loc[df['Genero_favorito'] == 'Ficcao cientifica'])