In [3]:
import pandas as pd

In [5]:
df = pd.read_csv('Clientes_VI.csv')

In [7]:
df.head(5)

,nome,cpf,idade,data,endereco,estado
0,Sr. Vitor Gabriel Silva,640.719.385-01,90,06/12/1933,"Trevo Emanuel Silva, 482\nVila Tirol\n47847085...",Rondônia
1,Calebe Santos,651.297.384-46,40,06/03/1984,"Recanto Moraes, 7\nErnesto Nascimento\n96497-6...",Rio de Janeiro
2,Evelyn Pires,107.643.528-90,80,09/03/1944,"Travessa de Caldeira, 237\nSanta Terezinha\n84...",Sergipe
3,Maria Julia Castro,164.750.293-43,76,12/04/1947,"Residencial de Pereira, 20\nJatobá\n62127-165 ...",Pernambuco
4,Arthur da Rosa,085.167.249-30,53,16/04/1970,"Parque Almeida, 66\nVila Suzana Segunda Seção\...",Santa Catarina

In [9]:
df['estado'] = df['estado'].str.upper()

In [11]:
df['CPF'] = df['cpf'].apply(lambda cpf: f'{cpf[:3]}.***.***.-{cpf[-2:]}')

In [13]:
df.drop('cpf', axis=1, inplace=True)

In [15]:
df['data'] = pd.to_datetime(df['data'], dayfirst=True, errors='coerce')

In [17]:
df['estado'] = df['estado'].str.upper()

In [19]:
df.rename(columns={'estado': 'Cidade'}, inplace=True)

In [21]:
df['Estado'] = df['endereco'].apply(lambda x: x.split('/')[-1])

In [234]:
df['CEP'] = df['endereco'].apply(lambda x: x.split('\n')[2::1])

In [238]:
df['endereco'] = df['endereco'].apply(lambda x: x.split('\n')[:])

In [262]:
df.rename(columns={'cidade': 'CIDADE', 'estado': 'ESTADO'}, inplace=True)

In [268]:
reorganize = ['NOME', 'DATA', 'IDADE', 'CPF', 'Cidade', 'Estado', 'ENDERECO', 'CEP']

In [270]:
df = df[reorganize]

In [272]:
df

,NOME,DATA,IDADE,CPF,Cidade,Estado,ENDERECO,CEP
0,Sr. Vitor Gabriel Silva,1933-12-06,90,640.***.***.-01,RONDÔNIA,AP,"[Trevo Emanuel Silva, 482, Vila Tirol, 4784708...",[47847085 Pereira / AP]
1,Calebe Santos,1984-03-06,40,651.***.***.-46,RIO DE JANEIRO,PB,"[Recanto Moraes, 7, Ernesto Nascimento, 96497-...",[96497-621 da Rosa / PB]
2,Evelyn Pires,1944-03-09,80,107.***.***.-90,SERGIPE,TO,"[Travessa de Caldeira, 237, Santa Terezinha, 8...",[84390313 Sales / TO]
3,Maria Julia Castro,1947-04-12,76,164.***.***.-43,PERNAMBUCO,AL,"[Residencial de Pereira, 20, Jatobá, 62127-165...",[62127-165 Gomes de Santos / AL]
4,Arthur da Rosa,1970-04-16,53,085.***.***.-30,SANTA CATARINA,SE,"[Parque Almeida, 66, Vila Suzana Segunda Seção...",[09805-686 Santos / SE]
...,...,...,...,...,...,...,...,...
1012,Lívia Nunes,1975-03-14,49,742.***.***.-23,BAHIA,PI,"[Passarela de Porto, 65, Pousada Santo Antonio...",[35531-299 Mendes do Amparo / PI]
1013,Joana Silva,1999-09-19,24,349.***.***.-57,PERNAMBUCO,PE,"[Chácara Miguel Fogaça, Laranjeiras, 52800515 ...",[52800515 Souza Verde / PE]
1014,Luigi Porto,1980-08-18,43,826.***.***.-83,ESPÍRITO SANTO,PI,"[Parque de Santos, 88, São João, 60112-833 Rod...",[60112-833 Rodrigues / PI]
1015,Letícia da Mata,1976-08-04,47,308.***.***.-31,RIO DE JANEIRO,PR,"[Aeroporto da Paz, 54, Vila São Dimas, 26750-5...",[26750-505 Costa / PR]
1016,Dr. Thomas Nunes,1942-08-14,81,967.***.***.-46,PIAUÍ,SE,"[Vereda da Mota, 37, Vila Da Luz, 50836-481 Mo...",[50836-481 Moura / SE]

In [275]:
df.to_csv('Clientes_final_version.csv', index=False)